### ISSUE TITLE
Update to 0.8.6

### ISSUE THREAD

**Issue by Rorrenoa** [julr/htbah#1]
Hallöchen,

kann es sein das es mit der aktuellen 0.8.6 Version nicht mehr funktioniert?

**Comment by julr** [comment]
Ich habe seit Ewigkeiten meine FVTT Installation nicht mehr aktualisiert. Ich schau mir das mal an, danke für den Hinweis.

**Comment by dididotwo** [comment]
Falls es inzwischen behoben war mit 0.8.9 Funktioniert es immernoch/wieder nicht
