### ISSUE TITLE
Update to V10

### ISSUE THREAD

**Issue by Dicio83** [julr/htbah#3]
Moin,
ich bin gerade erst in VTT. Hauptsächlich für ein anderes Regelsystem. Da HTBAH aber ein so schönes Regelwerk für Einsteiger ist, würde es mich freuen das System irgendwann auf V10 spielen zu können :-)

**Comment by julr** [comment]
Da ich keine digitale Spielleitung mehr mache, werde ich dieses Projekt nicht weiter verfolgen.
